//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LobanovEntities : DbContext
    {
        private static LobanovEntities _context;
        public LobanovEntities()
            : base("name=LobanovEntities")
        {
        }
    
        public static LobanovEntities GetContext() 
        {
            if (_context == null) _context = new LobanovEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Flat> Flat { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Rieltor> Rieltor { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Trade> Trade { get; set; }
    }
}
